baseURL = "" 
languageCode = "en-us"
title = "AWS Lambda - Serverless"
theme = "ananke"

[params.lambdaComments]
endpoint = "https://ndu5xjubrk.execute-api.us-east-2.amazonaws.com/default/piyush-comments-post"
